#!/bin/sh

COMMAND=${1-"help"}
shift

echo '[BUILD]'
docker build --tag="sw-builder" --progress="quiet" .

echo '[RUN]'
docker run --network="host" --volume="$(pwd):/app" --rm sw-builder bin/$COMMAND $@