<h1><?= i18n('Legal Notice') ?></h1>

<section>
    <h2><?= i18n('Website Owner') ?></h2>
    <address>
        Nicolas Fasano<br>
        ul. Vezhen 22, 1421 Sofia<br>
        <?= i18n('Bulgaria') ?>
    </address>
</section>

<section>
    <h2><?= i18n('Contact') ?></h2>
    <address>
        <?= i18n('Email') ?>: fasano.nm@gmail.com<br>
        <?= i18n('Phone') ?>: <?= i18n('+359 87 833 1171') ?>
    </address>
</section>

<section>
    <h2><?= i18n('Disclaimer') ?></h2>
    <p>
        <?= i18n('This website provides general information. While we aim to keep the information up to date, we make no warranties of any kind about its completeness or accuracy.') ?>
    </p>
</section>