<h1><?= i18n('About us') ?></h1>

<section>
    <article>
        <h2><?= i18n('Our values') ?></h2>
        <p>
            <?= i18n('We share one essential value: understanding. For us, everything starts there. Truly grasping a need, a context, a person — that’s what allows us to build solutions that are meaningful, relevant, and sustainable.') ?>
        </p>
        <p>
            <?= i18n('One of us approaches this as a rational obsession: if the solution doesn’t fit, it means something is still unclear — and he won’t stop until he gets it right. The other brings a more intuitive, human dimension, with genuine attentiveness and active kindness that turn every exchange into a space for co-creation. Together, we strike a balance between precision and empathy, between high standards and real connection.') ?>
        </p>
    </article>
</section>

<section>
    <article>
        <img src="/resources/images/nicolas.webp" alt="<?= i18n("Nicolas' Picture") ?>">
        <h2>Nicolas</h2>
        <h3><?= i18n('Development & Technical Consulting') ?></h3>
        <p>
            <?= i18n('I’ve worked in places with a strong corporate mindset — not big companies, but environments with too much posturing and too little substance. Over time, that drained the joy out of the work. Now, I focus on working with entrepreneurs and teams who know their craft, make decisions fast, and value straight talk. Building over buzzwords.') ?>
        </p>
    </article>

    <article>
        <img src="/resources/images/amandine.jpg" alt="<?= i18n("Amandine's Picture") ?>">
        <h2>Amandine</h2>
        <h3><?= i18n('Quality Assurance & Customer Relations') ?></h3>
        <p>
            <?= i18n('I\'m the type who notices the small things others miss — what\'s off or what\'s lacking — not out of habit, but because it matters to me. Whether it\'s a line of code or a conversation with a client, I believe the details make the difference. I\'ve nurtured this attention over time, probably fed by my passion for the arts: watercolour, bookmaking, saxophone, theatre… crafts where you can\'t fake it and every move counts. Today, I bring that same level of care to the quality of our work and our client relationships.') ?>
        </p>
    </article>
</section>

<hr>

<section>
    <h3><?= i18n('You want to work with us?') ?></h3>
    <p><?= i18n('Check out our services:') ?></p>
    <a class="button" href="<?= i18n('/our-services') ?>"><?= i18n('Our Services') ?></a>
</section>
<!-- <section>
    <h3>You want to work with us?</h3>
    <p>Let's talk about it. We'll help you figure out the right approach.</p>
    <a class="button" href="/contact-us">Get in Touch</a>
</section> -->