<?php $template = 'alternate.phtml' ?>

<h1><?= i18n('Contact us') ?></h1>

<section>
    <img src="/resources/logo-alt.webp" alt="Software Weavers' Logo">
    <p>
        <i class="fa-solid fa-envelope"></i>
        <a href="mailto:weavers.software@gmail.com">weavers.software@gmail.com</a>
    </p>
    <p>
        <i class="fa-solid fa-phone"></i>
        <a href="tel:+359878331171">+359 87 947 3758</a>
    </p>
</section>
