<?php $template = 'alternate.phtml' ?>

<section>
    <article>
        <img src="/resources/logo-alt.webp" alt="Software Weavers' Logo">
        <h1><?= i18n('Contact us') ?></h1>
        <p>We'd love to hear from you</p>
    </article>
    <hr>
    <aside>
        <h2>Contact Information</h2>
        <address>
            <div>
                <i class="fa-solid fa-envelope"></i>
                <a href="mailto:weavers.software@gmail.com">weavers.software@gmail.com</a>
            </div>
            <div>
                <i class="fa-solid fa-phone"></i>
                <a href="tel:+359878331171">+359 87 947 3758</a>
            </div>
        </address>
    </aside>
</section>

