<section>
    <article>
        <img src="/resources/logo-alt.webp" alt="<?= i18n("A loom inside a computer screen") ?>">
        <h1><?= i18n('Contact us') ?></h1>
        <p><?= i18n('We\'d love to hear from you!') ?></p>
    </article>
    <hr>
    <aside>
        <h2><?= i18n('Contact Information') ?></h2>
        <address>
            <div>
                <img src="/resources/email.webp" alt="<?= i18n("Email icon") ?>">
                <a href="mailto:<?= i18n('weavers.software@gmail.com') ?>"><?= i18n('weavers.software@gmail.com') ?></a>
            </div>
            <div>
                <img src="/resources/call.webp" alt="<?= i18n("Phone icon") ?>">
                <a href="tel:<?= i18n('+359 87 947 3758') ?>"><?= i18n('+359 87 947 3758') ?></a>
            </div>
        </address>
    </aside>
</section>

