<section>
    <article>
        <h1><?= i18n('We weave software that just works.') ?></h1>
        <p><?= i18n('Custom software built with craftsmanship.') ?></p>
        <a class="button" href="<?= i18n('/contact-us') ?>"><?= i18n('Get in Touch') ?></a>
    </article>
    <aside>
        <img src="/resources/images/index/group-work.webp" alt="<?= i18n("Craftsmans at work in a workshop mixing old and modern tools") ?>">
    </aside>
</section>

<hr>

<section>
    <article>
        <h2><?= i18n('Who we are') ?></h2>
        <p><?= i18n('We\'re a small team of developers who treat code like craft. Focused on quality, precision, and long-term maintainability.') ?></p>
        <div>
            <img loading="lazy" src="/resources/images/nicolas.webp" alt="<?= i18n("Nicolas' Picture") ?>">
            <h3>Nicolas</h3>
            <h4><?= i18n('Development & Technical Consulting') ?></h4>
        </div>
        <div>
            <img loading="lazy" src="/resources/images/amandine.webp" alt="<?= i18n("Amandine's Picture") ?>">
            <h3>Amandine</h3>
            <h4><?= i18n('Quality Assurance & Customer Relations') ?></h4>
        </div>
        <div>
            <a class="button" href="<?= i18n('/about-us') ?>"><?= i18n('About us') ?></a>
        </div>
    </article>

    <hr>

    <aside>
        <h2><?= i18n('What we offer') ?></h2>
        <div>
            <h3><?= i18n('Template-Based Websites') ?></h3>
            <p><?= i18n('Fast, effective websites using clean, modern templates.') ?></p>
            <img loading="lazy" src="/resources/images/index/monitor.png" alt="<?= i18n("A computer screen") ?>">
        </div>
        <div>
            <h3><?= i18n('Software Setup & Support') ?></h3>
            <p><?= i18n('We help you choose, configure, and implement the right software solutions.') ?></p>
            <img loading="lazy" src="/resources/images/index/handshake.png" alt="<?= i18n("A handshake") ?>">
        </div>
        <div>
            <h3><?= i18n('Custom Web & Software Development') ?></h3>
            <p><?= i18n('Purpose-built solutions for your business.') ?></p>
            <img loading="lazy" src="/resources/images/index/jigsaw.png" alt="<?= i18n("A hand completing a 4-piece jigsaw") ?>">
        </div>
        <div>
            <a class="button" href="<?= i18n('/our-services') ?>"><?= i18n('Our services') ?></a>
        </div>
    </aside>
</section>
