<?php $template = 'alternate.phtml' ?>

<section>
    <article>
        <h1>We weave software that just works.</h1>
        <p>Custom software built with craftsmanship.</p>
        <a class="button" href="/contact-us">Get in Touch</a>
    </article>
    <aside>
        <img src="/resources/hero.png" alt="Hero image">
    </aside>
</section>

<hr>

<section>
    <article>
        <h2>Who we are</h2>
        <p>We're a small team of developers who treat code like craft. Focused on quality, precision, and long-term maintainability.</p>
        <div>
            <img src="/resources/nicolas.png" alt="Nicolas' Picture">
            <h3>Nicolas</h3>
            <h4>Development & Technical Consultation</h4>
        </div>
        <div>
            <img src="/resources/amandine.jpg" alt="Amandine's Picture">
            <h3>Amandine</h3>
            <h4>Quality Assurance & Customer Relations</h4>
        </div>
        <a class="button" href="/about-us">About us</a>
    </article>

    <hr>

    <aside>
        <h2>What we offer</h2>
        <div>
            <h3>Custom Software Development</h3>
            <p>Scalable, purpose-built solutions for your business.</p>
            <img src="/resources/puzzle-piece.png" alt="A puzzle piece">
        </div>
        <div>
            <h3>Web & Mobile Apps</h3>
            <p>Cross-platform applications, beautifully made and robust.</p>
            <img src="/resources/world-wide-web.png" alt="The world wide web globe">
        </div>
        <div>
            <h3>Systems Integration</h3>
            <p>Connect and automate your workflows through tailored APIs and backend logic.</p>
            <img src="/resources/settings.png" alt="A cog">
        </div>
        <a class="button" href="/our-services">Our services</a>
    </aside>
</section>
