<section>
    <article>
        <h1><?= i18n('We weave software that just works.') ?></h1>
        <p><?= i18n('Custom software built with craftsmanship.') ?></p>
        <a class="button" href="<?= i18n('/contact-us') ?>"><?= i18n('Get in Touch') ?></a>
    </article>
    <aside>
        <img src="/resources/ChatGPT-group-work-2.webp" alt="Hero image">
    </aside>
</section>

<hr>

<section>
    <article>
        <h2><?= i18n('Who we are') ?></h2>
        <p><?= i18n('We\'re a small team of developers who treat code like craft. Focused on quality, precision, and long-term maintainability.') ?></p>
        <div>
            <img src="/resources/nicolas.webp" alt="Nicolas' Picture">
            <h3>Nicolas</h3>
            <h4><?= i18n('Development & Technical Consulting') ?></h4>
        </div>
        <div>
            <img src="/resources/amandine.webp" alt="Amandine's Picture">
            <h3>Amandine</h3>
            <h4><?= i18n('Quality Assurance & Customer Relations') ?></h4>
        </div>
        <a class="button" href="<?= i18n('/about-us') ?>"><?= i18n('About us') ?></a>
    </article>

    <hr>

    <aside>
        <h2><?= i18n('What we offer') ?></h2>
        <div>
            <h3><?= i18n('Template-Based Websites') ?></h3>
            <p><?= i18n('Fast, effective websites using clean, modern templates.') ?></p>
            <img src="/resources/monitor.png" alt="A computer screen">
        </div>
        <div>
            <h3><?= i18n('Software Setup & Support') ?></h3>
            <p><?= i18n('We help you choose, configure, and implement the right software solutions.') ?></p>
            <img src="/resources/handshake-alt.png" alt="A handshake">
        </div>
        <div>
            <h3><?= i18n('Custom Web & Software Development') ?></h3>
            <p><?= i18n('Purpose-built solutions for your business.') ?></p>
            <img src="/resources/jigsaw-lighter.png" alt="A hand completing a 4-piece jigsaw">
        </div>
        <a class="button" href="<?= i18n('/our-services') ?>"><?= i18n('Our services') ?></a>
    </aside>
</section>
