<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Software Weavers</title>
    <link rel="shortcut icon" href="/resources/favicon.png" type="image/x-icon">
    <meta name="description" content="At Software Weavers, we specialize in creating thoughtful, handcrafted websites that combine design, functionality, and user experience. We take pride in delivering quality digital solutions, tailored to meet the unique needs of your business.">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
        rel="stylesheet">

    <script defer src="https://kit.fontawesome.com/3aad7a6632.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="/resources/css/reset.css">
    <link rel="stylesheet" href="/resources/css/default.css">
</head>

<body>
    <header>
        <img src="/resources/logo.webp" alt="Software Weavers' Logo">
        <nav>
            <a class="button" href="/">Home</a>
            <a class="button" href="/services">Services</a>
            <!-- <a class="button" href="/quality-charter">Quality Charter</a> -->
            <!-- <a class="button" href="/contact">Contact</a> -->
            <a class="button" href="<?= i18n('/about') ?>"><?= i18n('About') ?></a>
            <a class="button" href="/blog">Blog</a>
        </nav>
    </header>
    <main>
        <?= $content ?>
    </main>
    <footer>
        <nav>
            <a class="button" href="/legal-notice">Legal notice</a>
            <a class="button" href="/privacy-policy">Privacy Policy</a>
            <a class="button" href="/cookies-policy">Cookies Policy</a>
            <a class="button" href="/sitemap">Sitemap</a>
        </nav>
        <img src="/resources/logo-name.jpg" alt="Software Weavers' Logo">
    </footer>
</body>
</html>