<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><?= i18n('Software Weavers') ?></title>
    <link rel="shortcut icon" href="/resources/favicon.png" type="image/x-icon">
    <meta name="description" content="<?= i18n('At Software Weavers, we specialize in creating thoughtful, handcrafted websites that combine design, functionality, and user experience. We take pride in delivering quality digital solutions, tailored to meet the unique needs of your business.') ?>">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap">

    <link rel="stylesheet" href="/resources/css/reset.css">
    <link rel="stylesheet" href="/resources/css/default.css">
    <link rel="stylesheet" href="/resources/css/<?= $filename ?>.css">
</head>

<body>
    <header>
        <a href="/">
            <img src="/resources/images/tdn-logo-6.png" alt="<?= i18n('Software Weavers\' Logo') ?>">
        </a>
        <nav>
            <?= nav_link('/', 'Home', $filename === 'index' ? '/' : $filepath) ?>
            <?= nav_link('/our-services', 'Services', "/$filepath") ?>
            <?= nav_link('/about-us', 'About', "/$filepath") ?>
            <?= nav_link('/contact-us', 'Contact', "/$filepath") ?>
        </nav>
    </header>
    <main>
        <?= $content ?>
        <div id="palette">
            <div style="background-color: #F5F2E9">#F5F2E9</div>
            <div style="background-color: #59402A">#59402A</div>
            <div style="background-color: #733729">#733729</div>
            <div style="background-color: #9e7559">#9e7559</div>
            <div style="background-color: #807839">#807839</div>
            <div style="background-color: #5e5c62">#5e5c62</div>
            
            <div style="background-color: #a74d38">#a74d38</div>
            <div style="background-color: #C7926D">#C7926D</div>
            <div style="background-color: #A99F54">#A99F54</div>
            <div style="background-color: #7B7981">#7B7981</div>
        </div>
    </main>
    <footer>
        <nav>
            <?= nav_link('/legal/notice', 'Legal Notice') ?>
            <?= nav_link('/legal/privacy', 'Privacy Policy') ?>
        </nav>

        <a href="/">
            <img src="/resources/images/tdn-logo-2.png" alt="<?= i18n('Software Weavers\' Logo') ?>">
        </a>

        <!-- <a href="/" id="logo"><?= i18n('Software Weavers') ?></a> -->

        <!-- <div>Icons made by <a href="https://www.flaticon.com/authors/kerismaker" title="kerismaker"> kerismaker </a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com'</a></div> -->
        <!-- <div> Icons made by <a href="https://www.freepik.com" title="Freepik"> Freepik </a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com'</a></div> -->
        <!-- <div> Icons made by <a href="https://www.freepik.com" title="Freepik"> Freepik </a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com'</a></div> -->
        <!-- <a href="https://www.flaticon.com/free-icons/strategy" title="strategy icons">Strategy icons created by DinosoftLabs - Flaticon</a> -->
    </footer>
</body>
</html>